import { load } from 'cheerio'
import type { AnyNode, Element } from 'domhandler'
import type { Cheerio, CheerioAPI } from 'cheerio'
import { NODE_ID_ATTRIBUTE } from '@opencraw/core'

/**
 * One level of a node's ancestry, root first: the element's own shape (tag,
 * id, classes, attributes) plus where it sits among its same-tag siblings.
 * Built over parsed HTML (cheerio), never a live DOM: the studio infers
 * selectors from the snapshot the server captured, not from a browser
 * window in the UI process (studio plan §3.1/§3.2, issue #91).
 */
export interface DomPathLevel {
  tag:          string
  id?:          string
  classes:      string[]
  attrs:        Record<string, string>
  /** 1-based position among same-tag siblings under the same parent (an `nth-of-type` index). */
  index:        number
  /** How many same-tag siblings share the parent, `index` included. */
  siblingCount: number
}

/** A node's whole ancestry, root first, the node itself last. */
export type DomPath = DomPathLevel[]

const GENERATED_ID = /^(?:react-|radix-|:r|ember|css-|mui-|headlessui-)/i

/**
 * The path from the document root to `node`, one level per ancestor. Two
 * elements that share an ancestor produce identical levels up to that
 * ancestor and diverge exactly where their parents stop being the same node
 * — `list-inference.algorithm.ts` leans on that to find the nearest pair of
 * siblings two picks belong to, without ever touching cheerio again.
 *
 * @param $ - The parsed document.
 * @param node - The element to describe.
 * @returns The path, root first.
 */
export function domPathOf ($: CheerioAPI, node: Cheerio<AnyNode>): DomPath {
  const chain: Cheerio<AnyNode>[] = []
  let current: Cheerio<AnyNode> | undefined = node
  while (current !== undefined && current.length > 0 && isElement(current.get(0))) {
    chain.unshift(current)
    const parent: Cheerio<AnyNode> = current.parent()
    current = parent.length > 0 ? parent : undefined
  }

  return chain.map(element => levelOf($, element))
}

function levelOf ($: CheerioAPI, element: Cheerio<AnyNode>): DomPathLevel {
  const node = element.get(0) as Element
  const tag = node.tagName.toLowerCase()
  const attrs: Record<string, string> = {}
  const entries = Object.entries(node.attribs ?? {})
  for (const [name, value] of entries) attrs[name] = value
  const classes = (attrs.class ?? '').split(/\s+/).filter(token => token.length > 0)
  const siblings = element.parent().length > 0 ? element.parent().children(tag) : $.root().children(tag)
  const index = siblings.toArray().indexOf(node) + 1

  return { tag, id: attrs.id, classes, attrs, index: Math.max(index, 1), siblingCount: Math.max(siblings.length, 1) }
}

function isElement (node: AnyNode | undefined): node is Element {
  return node !== undefined && node.type === 'tag'
}

/**
 * Whether `id` looks handed by a framework (`react-`, a CSS-module or a
 * `radix-`/`mui-` autogenerated one) rather than by the site's own markup —
 * `class-token.policy.ts` has the equivalent check for class tokens, kept
 * separate because ids and classes are ranked at different tiers.
 */
export function isStableId (id: string): boolean {
  return id.length > 0 && !GENERATED_ID.test(id)
}

/**
 * Whether `path` failed to reach the real document root. `domPathOf` walks
 * up through cheerio's own `.parent()`, which (matching real DOM semantics)
 * never crosses from a `<template>`'s content into the light DOM outside
 * it — a `<template shadowrootmode>` is exactly declarative shadow DOM, the
 * only shadow-DOM shape that can show up in static, server-captured markup
 * at all (imperative `attachShadow()` content never serialises into
 * `page.content()`/a fetched response in the first place, so that case
 * cannot reach this slice and needs no separate detection). A path whose
 * first level is not `html` was cut short at exactly this kind of boundary:
 * v1 does not pierce it, so callers report a clear "shadow DOM is not
 * supported" error instead of building ancestor-based candidates over a
 * chain that stops partway up.
 */
export function crossesShadowRoot (path: DomPath): boolean {
  return path.length === 0 || path[0].tag !== 'html'
}

/** Parses `html` and returns cheerio's API, for callers that need more than one path from the same document. */
export function parseDocument (html: string): CheerioAPI {
  return load(html)
}

/**
 * The path to the element the snapshot stamped with `nodeId` (its
 * `data-oc-node` attribute — `@opencraw/core`'s `NODE_ID_ATTRIBUTE`,
 * `packages/studio/src/page-snapshot/rewrite-document.mapper.ts`). This is
 * how a click in the content pane's iframe — which only ever needs to read
 * that one attribute off the element the user clicked — turns into
 * something `selector-inference`'s other algorithms can work with, without
 * the browser-side picker script needing to know anything about ancestry,
 * classes or candidate ranking itself.
 *
 * @param html - The snapshot document (already stamped with node ids).
 * @param nodeId - The `data-oc-node` value to find.
 * @returns The node's path, or `undefined` when no element carries that id.
 */
export function pathToNode (html: string, nodeId: string): DomPath | undefined {
  const $ = parseDocument(html)
  const found = $(`[${NODE_ID_ATTRIBUTE}="${cssAttributeValue(nodeId)}"]`)

  return found.length === 0 ? undefined : domPathOf($, found.first())
}

function cssAttributeValue (value: string): string {
  return value.replaceAll('\\', String.raw`\\`).replaceAll('"', String.raw`\"`)
}
