export { domPathOf, isStableId, crossesShadowRoot, parseDocument, pathToNode } from './dom-path.model'
export type { DomPath, DomPathLevel } from './dom-path.model'
export { takeKindFor } from './take-kind.policy'
export { isStableClassToken, stableClasses, sameClassSignature } from './class-token.policy'
export { ShadowDomUnsupportedError } from './shadow-dom.error'
export { candidatesFor } from './selector-candidates.algorithm'
export type { SelectorCandidate, CandidateTier } from './selector-candidates.algorithm'
export { rankCandidates, bestCandidate } from './selector-ranking.policy'
export type { RankedCandidate } from './selector-ranking.policy'
export { inferList } from './list-inference.algorithm'
export type { ListInferenceResult } from './list-inference.algorithm'
