export { createCrawler, recipeRuns, variantLabel, workFrom, createWorkInbox, sessionStateOf, defaultOutcome, errorKindOf } from './crawl-execution'
export { AccessBroker, AccessConfigError, ACCESS_PRESETS, loadAccessConfig, accessConfigSchema, accessConfigJsonSchema, throttleConfigSchema } from './access'
export type { AccessConfig, AccessProfile, AccessPlugin, AccessLease, LeaseRequest, PluginLeaseRequest, ProxySettings, AccessPreset } from './access'
export type { SessionStateOptions, Crawler, CrawlOptions, CrawlReport, RecipeReport, RecipeRun, WorkItem, WorkSource, WorkOptions, WorkReport, WorkList, WorkInbox, WorkItemResult, SubmitOptions, WindowsPolicy, WorkOutcome, ErrorKind } from './crawl-execution'
export { loadRecipeSet, loadRecipes, readRecipeSource, bindRecipeSet, RecipeSet, RecipeBindingError, validateBinding, bindingsAt } from './recipe-loading'
export type { RecipeSetSource, RecipeSource, RecipeBytes, RecipeDocument, BindingIssue, HookUse } from './recipe-loading'
export { parseInputRecipe, parseOutputRecipe, RecipeValidationError, inputRecipeJsonSchema, outputRecipeJsonSchema, inputRecipeSchema, outputRecipeSchema, retryRuleSchema, BODY_KINDS } from './recipe-schema'
export type { InputRecipe, OutputRecipe, FieldSpec, Step, StepType, MappingRule, TransformRule, ErrorPolicy, PaginateNext, SessionSpec, SessionAccess, CaptchaSettings, CaptchaStep, CaptchaCheck, CaptchaSubmitStep, RecipeMatrix, VarValue, RetryRule, RecipeIssue, MissingPolicy, BodyKind } from './recipe-schema'
export type { Hook, HookMap, HookContext } from './hooks'
export { UnknownHookError } from './hooks'
export type { FieldTrace, MappingTrace, OutputRecord } from './output-mapping'
export { RecordRejectedError, MappingFailedError, resolveMissingPolicy, isMissing } from './output-mapping'
export type { RecordSink, SinkSummary, MemorySink, DedupeScope } from './record-sink'
export { memorySink, jsonLinesSink } from './record-sink'
export type { CrawlEvent, CrawlListener } from './crawl-events'
export { traceLine } from './crawl-events'
export type { BrowserSessionConfig, SessionOptions } from './browser-session'
export { BrowserClient, BrowserSession, BrowserProfiles } from './browser-session'
export { HttpClient, HttpError } from './http-session'
export { HostAllowlist, HostNotAllowedError } from './host-allowlist'
export type { HttpClientOptions, HttpRequest, HttpResponse, HttpBody } from './http-session'
export { tryParseJson, selectHtml, countMatches, matchesOf, NODE_ID_ATTRIBUTE } from './selection'
export type { HtmlMatch } from './selection'
export { readPdf, PdfReadError, analyzeTables, findTables, pdfText, isPdfDocument, rowsOfCells, parseRegion, regionSelector, regionText, regionCells, isInsideRegion } from './pdf-document'
export type { DocumentRegion, PdfRegionMatch, PositionedBox } from './pdf-document'
export type { PdfDocument, PdfPage, PdfRow, PdfCell, PositionedText, PdfTable, TableQuery, TableAlign, TableDiagnostics, TableBandDiagnostics } from './pdf-document'
export { parseCsv, detectDelimiter, csvWorkbook, readXlsxWorkbook, findGridTables, fillDown, workbookText, isWorkbookDocument, htmlTableSheets } from './workbook-document'
export { readMarkdown } from './markdown-document'
export { readYaml } from './yaml-document'
export { parseXml, selectXpath, takeFromXml, isXmlDocument, htmlAsXml } from './xml-document'
export type { XmlDocument, XpathOptions, XpathValue } from './xml-document'
export { findDeckTables, deckText, isDeckDocument, readPptxDeck, deckRegionText } from './deck-document'
export type { DeckDocument, DeckSlide, DeckShape, DeckChart, DeckTable, DeckTableQuery, DeckRegionMatch } from './deck-document'
export type { WorkbookDocument, WorkbookCell, Sheet, CsvFormat, GridTable, GridTableQuery } from './workbook-document'
export { StepFailure, HostThrottle, DEFAULT_RETRY_RULE } from './step-flow'
export type { ThrottleConfig, HostRule } from './step-flow'
export { TransformError } from './transformation'
export { diffRecords, diffOptionsFor, readableKey, readRecordsFile } from './record-diff'
export type { RecordDiff, RecordChange, FieldChange, DiffOptions, StoredRecord } from './record-diff'
export { CaptchaError, DEFAULT_CAPTCHA_SELECTOR, detectChallenge, manualCaptchaSolver } from './captcha'
export type { CaptchaSolver, CaptchaChallenge, CaptchaContext, CaptchaOutcome, CaptchaVerdict, CaptchaKind, CaptchaLog } from './captcha'
